version: '3.8'  

services:
  db:
    image: mysql:8.0  
    container_name: contactContaint 
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}  
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"  
    volumes:
      - ./data:/var/lib/mysql  

